version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend/logs:/app/logs
    depends_on:
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - ./promtail-config.yml:/etc/promtail-config.yml
      - ./Backend/logs:/var/log/app
    command: -config.file=/etc/promtail-config.yml
