// List of available cities/locations for the ride-hailing service
// This array contains major cities across the United States where the service operates
const locations = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "San Francisco",
    "Columbus",
    "Indianapolis",
    "Fort Worth",
    "Charlotte",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "Las Vegas",
    "Miami",
    "Atlanta",
    "Minneapolis",
    "Detroit",
    "Nashville",
    "Portland",
    "Oklahoma City",
    "Milwaukee",
    "Louisville",
    "Memphis",
    "Baltimore",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Kansas City",
    "Mesa",
    "Omaha",
    "Colorado Springs",
    "Raleigh",
    "Virginia Beach",
    "Long Beach",
    "Oakland",
    "Miami Beach",
    "New Orleans",
    "Cleveland",
    "Honolulu",
    "Tampa",
    "Orlando",
    "St. Louis",
    "Pittsburgh",
    "Cincinnati",
    "Anchorage",
    "Lexington",
    "Stockton",
    "St. Paul",
    "Toledo",
    "Madison",
    "Arlington",
    "Bakersfield",
    "Aurora",
    "Riverside",
    "Corpus Christi",
    "Henderson",
    "Saint Paul",
    "Greensboro",
    "Plano",
    "Lincoln",
    "Irvine",
    "Newark",
    "Durham",
    "Chula Vista",
    "Fort Wayne",
    "Jersey City",
    "St. Petersburg",
    "Laredo",
    "Buffalo",
    "Lubbock",
    "Chandler",
    "Scottsdale",
    "Reno",
    "Glendale",
    "Norfolk",
    "Winston-Salem",
    "North Las Vegas",
    "Gilbert",
    "Chesapeake",
    "Garland",
    "Irving",
    "Hialeah",
    "Fremont",
    "Boise",
    "Richmond",
    "Baton Rouge",
    "Spokane",
    "Des Moines",
    "Tacoma",
    "San Bernardino",
    "Modesto",
    "Fontana",
    "Birmingham",
    "Oxnard",
    "Fayetteville",
    "Moreno Valley",
    "Rochester",
    "Huntington Beach",
    "Salt Lake City",
    "Grand Rapids",
    "Amarillo",
    "Yonkers",
    "Montgomery",
    "Akron",
    "Little Rock",
    "Huntsville",
    "Augusta",
    "Port St. Lucie",
    "Grand Prairie",
    "Columbus",
    "Tallahassee",
    "Overland Park",
    "Tempe",
    "McKinney",
    "Mobile",
    "Cape Coral",
    "Shreveport",
    "Frisco",
    "Knoxville",
    "Brownsville",
    "Worcester",
    "Vancouver",
    "Fort Lauderdale",
    "Sioux Falls",
    "Ontario",
    "Chattanooga",
    "Providence",
    "Newport News",
    "Rancho Cucamonga",
    "Santa Rosa",
    "Oceanside",
    "Salem",
    "Elk Grove",
    "Garden Grove",
    "Pembroke Pines",
    "Peoria",
    "Eugene",
    "Corona",
    "Cary",
    "Springfield",
    "Fort Collins",
    "Jackson",
    "Alexandria",
    "Hayward",
    "Lancaster",
    "Lakewood",
    "Clarksville",
    "Palmdale",
    "Salinas",
    "Springfield",
    "Hollywood",
    "Pasadena",
    "Sunnyvale",
    "Macon",
    "Pomona",
    "Escondido",
    "Killeen",
    "Naperville",
    "Joliet",
    "Bellevue",
    "Rockford",
    "Savannah",
    "Paterson",
    "Torrance",
    "Bridgeport",
    "McAllen",
    "Mesquite",
    "Syracuse",
    "Midland",
    "Pasadena",
    "Murfreesboro",
    "Miramar",
    "Dayton",
    "Fullerton",
    "Olathe",
    "Orange",
    "Thornton",
    "Roseville",
    "Denton",
    "Waco",
    "Surprise",
    "Carrollton",
    "West Valley City",
    "Charleston",
    "Warren",
    "Hampton",
    "Gainesville",
    "Visalia",
    "Coral Springs"
];

// Export the locations array for use in other components
export default locations;
