"""Added Payment mode:payment_model

Revision ID: 8312f04e4b6d
Revises: 
Create Date: 2025-04-02 11:09:38.929859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8312f04e4b6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_table('ride_history')
    op.drop_table('favorite_location')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_mode', sa.String(length=50), nullable=False))

    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint('ride_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('ride_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'captain', ['captain_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ride_ibfk_1', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('ride_ibfk_2', 'captain', ['captain_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('duration',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('payment_mode')

    op.create_table('favorite_location',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ride_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pickup', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('destination', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], name='favorite_location_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_location_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ride_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ride_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('pickup', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('destination', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], name='ride_history_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='ride_history_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('location',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('latitude', mysql.FLOAT(), nullable=False),
    sa.Column('longitude', mysql.FLOAT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='location_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
