{
 "title": "Logs",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_users/2", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "captain Latency Metrics",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (flask_request_latency_seconds_sum{endpoint=~\"^captain\\\\..*\", method!=\"OPTIONS\"}) \n/\nsum by (endpoint) (flask_request_latency_seconds_count{endpoint=~\"^captain\\\\..*\", method!=\"OPTIONS\"})\n",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "flask_cpu_usage", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Req, count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(endpoint) (\n  flask_request_count_total{\n    method!=\"OPTIONS\", \n    endpoint!=\"prometheus_metrics\", \n    endpoint!=\"unknown\",\n    endpoint!=\"frontend_metrics\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Latency Metrics",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (flask_request_latency_seconds_sum{endpoint=~\"^user\\\\..*\", method!=\"OPTIONS\"}) \n/\nsum by (endpoint) (flask_request_latency_seconds_count{endpoint=~\"^user\\\\..*\", method!=\"OPTIONS\"})\n",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Errors / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({filename=\"/app/logs/app.log\"} |= \"ERROR\" [1m])"
    }
   ]
  },
  {
   "title": "Ride Latency Metrics",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (flask_request_latency_seconds_sum{endpoint=~\"^rides\\\\..*\", method!=\"OPTIONS\"}) \n/\nsum by (endpoint) (flask_request_latency_seconds_count{endpoint=~\"^rides\\\\..*\", method!=\"OPTIONS\"})\n",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Flask memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "flask_memory_usage", "legendFormat": "{{kubernetes_pod_name}}" },
    {}
   ]
  },
  {
   "title": "Avg cpu usage per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(flask_cpu_usage[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Paments & ratings latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (flask_request_latency_seconds_sum{endpoint=~\"^payments\\\\..*\", method!=\"OPTIONS\"}) \n/\nsum by (endpoint) (flask_request_latency_seconds_count{endpoint=~\"^payments\\\\..*\", method!=\"OPTIONS\"})\n",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Network data sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "rate(flask_network_sent[5m])", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Network data received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "rate(flask_network_received[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Ride Review logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/app/logs/app.log\"} |= `review` != `module=sql_logger`"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/app/logs/app.log\"} |= `ERROR`"
    }
   ]
  },
  {
   "title": "Trails",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum by (le) (rate(flask_request_latency_seconds_bucket{endpoint=\"frontend_metrics\", method=\"POST\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_exceptions_total[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}